# Generated by Django 3.2.18 on 2023-03-08 01:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficIntensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_threshold', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Minimum Threshold')),
                ('max_threshold', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Maximum Threshold')),
                ('intensity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrafficCharacterization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('intensity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.trafficintensity')),
            ],
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('length', models.DecimalField(decimal_places=4, max_digits=10)),
                ('characterization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.trafficcharacterization')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_speed', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Average Speed')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.roadsegment')),
            ],
        ),
    ]
