# Generated by Django 3.2.18 on 2023-03-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafficintensity',
            options={'verbose_name_plural': 'Traffic intensities'},
        ),
    ]
