# Generated by Django 3.2.18 on 2023-03-08 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_trafficintensity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='avg_speed',
            field=models.DecimalField(decimal_places=9, max_digits=10, verbose_name='Average Speed'),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='characterization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.trafficcharacterization'),
        ),
        migrations.AlterField(
            model_name='trafficintensity',
            name='max_threshold',
            field=models.DecimalField(decimal_places=9, max_digits=10, verbose_name='Maximum Threshold'),
        ),
        migrations.AlterField(
            model_name='trafficintensity',
            name='min_threshold',
            field=models.DecimalField(decimal_places=9, max_digits=10, verbose_name='Minimum Threshold'),
        ),
    ]
