# Generated by Django 3.2.18 on 2023-03-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20230308_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadsegment',
            name='length',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
    ]
