# Generated by Django 3.2.18 on 2023-03-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_alter_roadsegment_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='avg_speed',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Average Speed'),
        ),
        migrations.AlterField(
            model_name='trafficintensity',
            name='max_threshold',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Maximum Threshold'),
        ),
        migrations.AlterField(
            model_name='trafficintensity',
            name='min_threshold',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Minimum Threshold'),
        ),
    ]
