version: '3'

services:
  db:
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build: .
    volumes:
      - .:/django
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - 8000:8000
    image: api:django
    depends_on:
      - db

volumes:
    postgres_data: